cca plugin add org.apache.cordova.file
cca plugin add org.apache.cordova.inappbrowser
cca plugin add org.apache.cordova.keyboard
cca plugin add org.apache.cordova.network-information
cca plugin add org.apache.cordova.statusbar
cca plugin add org.chromium.bootstrap
cca plugin add org.chromium.common
cca plugin add org.chromium.i18n
cca plugin add org.chromium.navigation
cca plugin add org.chromium.polyfill.CustomEvent
cca plugin add org.chromium.polyfill.blob_constructor
cca plugin add org.chromium.polyfill.xhr_features
cca plugin add org.chromium.runtime
cca plugin add org.chromium.storage
